### ISSUE TITLE
find() does not find empty call node

### ISSUE THREAD

**Issue by ronxin** [Psycojoker/baron#75]
I try to find the first function call in a block of code:

    from redbaron import RedBaron
    red = RedBaron('f()')
    print red.find('call')

I was expecting an empty `CallNode` (i.e., `()`), but instead I got `None`.

However, `findAll` seems to be able to find empty call nodes:

    print red.findAll('call')[0]

which gives me `()` as expected.

Just wanted to confirm if this is intentional, as the behavior seems a bit counter-intuitive.

**Comment by Psycojoker** [comment]
Hello,

Not, it's definitively a bug. On a side note and for organization purpose I'm closing this ticket here and re-opening it on the redbaron github repository, see https://github.com/Psycojoker/redbaron/issues/90
